version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/node/app
      - node_modules:/node/app/node_modules
      - $HOME/.aws:/root/.aws
    environment:
      DEPLOY_STAGE: ${DEPLOY_STAGE}
      TRIGGER_BUCKET_NAME: ${TRIGGER_BUCKET_NAME}
      DESTINATION_BUCKET_NAME: ${DESTINATION_BUCKET_NAME}
volumes:
  node_modules:
    driver: 'local'
